FROM jenkins/jenkins:lts
USER root
RUN apt-get update && apt-get install -y curl apt-transport-https ca-certificates gnupg lsb-release docker.io
RUN curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add - && \
    echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && \
    apt-get update && apt-get install -y google-cloud-sdk kubectl
USER jenkins